template: true 
valuesFilePath: ./values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.myRepo.gitProvider }}
      path: {{ .Values.myRepo.path }}
      branches:
        include: master

  - name: myPropertyBag
    type: PropertyBag
    configuration:
      testCase: ''

pipelines:
  - name: test_pipeline
    steps:
      - name: step1
        type: Bash
        configuration:
          outputResources:
            - name: myPropertyBag
        execution:
          onExecute:
            - write_output myPropertyBag testCase='Test P_SYC_Pipelines_6196_001'

      - name: step2
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag
        execution:
          onExecute:
            - echo "CommitSha is $res_myPropertyBag_testCase"
