template: true 
valuesFilePath: ./values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.myRepo.gitProvider }}
      path: {{ .Values.myRepo.path }}
      buildOn:
        commit: true
      branches:
        include: master
  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: test_pipeline1
    steps:
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: myFirstRepo
          outputResources:
            - name: propertyBag
        execution:
          onExecute:
            - echo "P1"
            - write_output propertyBag "foo=$run_number"
            
  - name: test_pipeline2
    steps:
      - name: step2
        type: Bash
        configuration:
          inputResources:
            - name: propertyBag
              trigger: true
        execution:
          onExecute:
            - echo "P2"
            
  - name: test_pipeline3
    steps:
      - name: step3
        type: Bash
        execution:
          onExecute:
            - echo "P3_S3"
            - add_run_variables temp1="test data"
            - echo "$temp1"
      - name: step4
        type: Bash
        execution:
          onExecute:
            - echo "P3_S4"
            - echo "$temp1"
            - add_run_variables temp1=""
            - echo "$temp1"
