template: true 
valuesFilePath: ./values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.myRepo.gitProvider }}
      path: {{ .Values.myRepo.path }}
      branches:
        include: master

pipelines:
  - name: test_pipeline1
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo "P1"
            
  - name: test_pipeline2
    steps:
      - name: step2
        type: Bash
        execution:
          onExecute:
            - echo "P2"
            
  - name: test_pipeline3
    steps:
      - name: step3
        type: Bash
        execution:
          onExecute:
            - echo "P3"

  - name: test_pipeline4
    steps:
      - name: step4
        type: Bash
        execution:
          onExecute:
            - sleep 5;
            - echo "P4"
