template: true 
valuesFilePath: ./values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.myRepo.gitProvider }}
      path: {{ .Values.myRepo.path }}
      branches:
        include: master

pipelines:
  - name: test_pipeline1
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo "P_SYC_Pipelines_6196_001"
