template: true 
valuesFilePath: ./values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.myRepo.gitProvider }}
      path: {{ .Values.myRepo.path }}
  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2
  - name: cron_trigger
    type: CronTrigger
    configuration:
      interval: '00 13 * * *'
      branches:
       include: "master"

pipelines:
  - name: pipeline_scheduled_triggers
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: cron_trigger
        execution:
          onExecute:
            - printenv
  - name: test_pipeline1
    steps:
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: myFirstRepo
          outputResources:
            - name: propertyBag
        execution:
          onExecute:
            - echo "1"
            - write_output propertyBag "foo=$run_number"
