template: true 
valuesFilePath: ./values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.myRepo.gitProvider }}
      path: {{ .Values.myRepo.path }}
  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2
  - name: cron_trigger
    type: CronTrigger
    configuration:
      interval: '30 04 * * *'
      branches:
       include: "[A-Za-z0-9]+"
  - name: cron_trigger2
    type: CronTrigger
    configuration:
      interval: '30 04 * * *'
      branches:
       include: "[A-Za-z0-9]+"

pipelines:
  - name: pipeline_scheduled_triggers
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: cron_trigger
        execution:
          onExecute:
            - printenv
  - name: pipeline_scheduled_triggers2
    steps:
      - name: step_2
        type: Bash
        configuration:
          inputResources:
            - name: cron_trigger2
        execution:
          onExecute:
            - printenv
